source: .
destination: ./_site

baseurl: "/gdextension-docs"
url: "https://vorlac.github.io"
title: GDExtension Technical Documentation
description: Comprehensive technical documentation for Godot Engine's GDExtension C++ API

# Use minimal theme with GitHub-like styling
theme: jekyll-theme-primer
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: none  # Disable Rouge, we're using Prism.js
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Disable Rouge since we're using Prism.js
highlighter: none

# Site structure
permalink: pretty

# Default layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .sass-cache
  - .jekyll-cache
  - node_modules